-- сначала дропаем зависимые таблицы
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS friendship;
DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS mpa;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    login VARCHAR(255),
    name VARCHAR(255),
    birthday DATE,
    friendsStatus VARCHAR(255),
    friendsList INT,
    lickedFilms INT
);

CREATE TABLE films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    releaseDate DATE,
    mpa INTEGER,
    duration INTEGER
);

CREATE TABLE genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE mpa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE film_genres (
  film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
  genre_id INTEGER REFERENCES genres (id) ON DELETE RESTRICT,
  PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE friendship (
  user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
  friend_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE likes (
  user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
  film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, film_id)
);
