DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    login VARCHAR(255),
    name VARCHAR(255),
    birthday DATE,
    friendsStatus VARCHAR(255),
    friendsList INT,
    LickedFilms INT
);

DROP TABLE IF EXISTS films;

CREATE TABLE films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    releaseDate DATE,
    genre VARCHAR(255),
    MPA VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER Not NULL,
    name VARCHAR(255),
    description VARCHAR(255),
    releaseDate DATE,
    genre VARCHAR(255),
    MPA VARCHAR(255)
);
